spring:
  application:
    name: calmDesk

  # Gemini API 키는 application-secret.yaml 에서만 설정
  ai:
    google:
      genai:
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7

  config:
    import: optional:classpath:application-secret.yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 8080

jwt:
  expiration: 86400000